name: firebridge_extensions
version: 4.1.2
description: Extensions to the Discord API provided in nyxx, including pagination support and message sanitization. Forked to provide support for firebridge.
repository: https://github.com/OpenBonfire/firebridge_extensions
documentation: https://nyxx.l7ssha.xyz
issue_tracker: https://github.com/OpenBonfire/firebridge_extensions/issues
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  firebridge:
    path: ../firebridge
  http: ^1.1.0

dev_dependencies:
  coverage: ^1.0.3
  lints: ^3.0.0
  mockito: ^5.4.2
  test: ^1.17.0
