// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/data_channel.dart';
import 'api/media.dart';
import 'api/peer_connection.dart';
import 'api/types.dart';
import 'api/video_codec.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_H264DecoderPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerH264Decoder;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_H264EncoderPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerH264Encoder;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_RtcDataChannelPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcDataChannel;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_RtcMediaSenderPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcMediaSender;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_RtcPeerConnectionPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcPeerConnection;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_RtcRemoteTrackPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcRemoteTrack;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  H264Decoder
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerH264Decoder(
    dynamic raw,
  );

  @protected
  H264Encoder
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerH264Encoder(
    dynamic raw,
  );

  @protected
  RtcDataChannel
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcDataChannel(
    dynamic raw,
  );

  @protected
  RtcMediaSender
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcMediaSender(
    dynamic raw,
  );

  @protected
  RtcPeerConnection
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcPeerConnection(
    dynamic raw,
  );

  @protected
  RtcRemoteTrack
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcRemoteTrack(
    dynamic raw,
  );

  @protected
  H264Decoder
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerH264Decoder(
    dynamic raw,
  );

  @protected
  H264Encoder
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerH264Encoder(
    dynamic raw,
  );

  @protected
  RtcDataChannel
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcDataChannel(
    dynamic raw,
  );

  @protected
  RtcMediaSender
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcMediaSender(
    dynamic raw,
  );

  @protected
  RtcPeerConnection
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcPeerConnection(
    dynamic raw,
  );

  @protected
  RtcRemoteTrack
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcRemoteTrack(
    dynamic raw,
  );

  @protected
  H264Decoder
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerH264Decoder(
    dynamic raw,
  );

  @protected
  H264Encoder
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerH264Encoder(
    dynamic raw,
  );

  @protected
  RtcDataChannel
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcDataChannel(
    dynamic raw,
  );

  @protected
  RtcMediaSender
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcMediaSender(
    dynamic raw,
  );

  @protected
  RtcPeerConnection
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcPeerConnection(
    dynamic raw,
  );

  @protected
  RtcRemoteTrack
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcRemoteTrack(
    dynamic raw,
  );

  @protected
  RustStreamSink<DataChannelEvent> dco_decode_StreamSink_data_channel_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<PeerConnectionEvent>
  dco_decode_StreamSink_peer_connection_event_Sse(dynamic raw);

  @protected
  RustStreamSink<RemoteRtpPacket> dco_decode_StreamSink_remote_rtp_packet_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DecodedVideoFrame dco_decode_box_autoadd_decoded_video_frame(dynamic raw);

  @protected
  RtcConfig dco_decode_box_autoadd_rtc_config(dynamic raw);

  @protected
  DataChannelEvent dco_decode_data_channel_event(dynamic raw);

  @protected
  DecodedVideoFrame dco_decode_decoded_video_frame(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  IceConnectionState dco_decode_ice_connection_state(dynamic raw);

  @protected
  IceGatheringState dco_decode_ice_gathering_state(dynamic raw);

  @protected
  IceServer dco_decode_ice_server(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<IceServer> dco_decode_list_ice_server(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MediaKind dco_decode_media_kind(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  DecodedVideoFrame? dco_decode_opt_box_autoadd_decoded_video_frame(
    dynamic raw,
  );

  @protected
  PeerConnectionEvent dco_decode_peer_connection_event(dynamic raw);

  @protected
  PeerConnectionState dco_decode_peer_connection_state(dynamic raw);

  @protected
  RemoteRtpPacket dco_decode_remote_rtp_packet(dynamic raw);

  @protected
  RtcConfig dco_decode_rtc_config(dynamic raw);

  @protected
  SignalingState dco_decode_signaling_state(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  H264Decoder
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerH264Decoder(
    SseDeserializer deserializer,
  );

  @protected
  H264Encoder
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerH264Encoder(
    SseDeserializer deserializer,
  );

  @protected
  RtcDataChannel
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcDataChannel(
    SseDeserializer deserializer,
  );

  @protected
  RtcMediaSender
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcMediaSender(
    SseDeserializer deserializer,
  );

  @protected
  RtcPeerConnection
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcPeerConnection(
    SseDeserializer deserializer,
  );

  @protected
  RtcRemoteTrack
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcRemoteTrack(
    SseDeserializer deserializer,
  );

  @protected
  H264Decoder
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerH264Decoder(
    SseDeserializer deserializer,
  );

  @protected
  H264Encoder
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerH264Encoder(
    SseDeserializer deserializer,
  );

  @protected
  RtcDataChannel
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcDataChannel(
    SseDeserializer deserializer,
  );

  @protected
  RtcMediaSender
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcMediaSender(
    SseDeserializer deserializer,
  );

  @protected
  RtcPeerConnection
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcPeerConnection(
    SseDeserializer deserializer,
  );

  @protected
  RtcRemoteTrack
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcRemoteTrack(
    SseDeserializer deserializer,
  );

  @protected
  H264Decoder
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerH264Decoder(
    SseDeserializer deserializer,
  );

  @protected
  H264Encoder
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerH264Encoder(
    SseDeserializer deserializer,
  );

  @protected
  RtcDataChannel
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcDataChannel(
    SseDeserializer deserializer,
  );

  @protected
  RtcMediaSender
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcMediaSender(
    SseDeserializer deserializer,
  );

  @protected
  RtcPeerConnection
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcPeerConnection(
    SseDeserializer deserializer,
  );

  @protected
  RtcRemoteTrack
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcRemoteTrack(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<DataChannelEvent> sse_decode_StreamSink_data_channel_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<PeerConnectionEvent>
  sse_decode_StreamSink_peer_connection_event_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<RemoteRtpPacket> sse_decode_StreamSink_remote_rtp_packet_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DecodedVideoFrame sse_decode_box_autoadd_decoded_video_frame(
    SseDeserializer deserializer,
  );

  @protected
  RtcConfig sse_decode_box_autoadd_rtc_config(SseDeserializer deserializer);

  @protected
  DataChannelEvent sse_decode_data_channel_event(SseDeserializer deserializer);

  @protected
  DecodedVideoFrame sse_decode_decoded_video_frame(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  IceConnectionState sse_decode_ice_connection_state(
    SseDeserializer deserializer,
  );

  @protected
  IceGatheringState sse_decode_ice_gathering_state(
    SseDeserializer deserializer,
  );

  @protected
  IceServer sse_decode_ice_server(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<IceServer> sse_decode_list_ice_server(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MediaKind sse_decode_media_kind(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  DecodedVideoFrame? sse_decode_opt_box_autoadd_decoded_video_frame(
    SseDeserializer deserializer,
  );

  @protected
  PeerConnectionEvent sse_decode_peer_connection_event(
    SseDeserializer deserializer,
  );

  @protected
  PeerConnectionState sse_decode_peer_connection_state(
    SseDeserializer deserializer,
  );

  @protected
  RemoteRtpPacket sse_decode_remote_rtp_packet(SseDeserializer deserializer);

  @protected
  RtcConfig sse_decode_rtc_config(SseDeserializer deserializer);

  @protected
  SignalingState sse_decode_signaling_state(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerH264Decoder(
    H264Decoder self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerH264Encoder(
    H264Encoder self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcDataChannel(
    RtcDataChannel self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcMediaSender(
    RtcMediaSender self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcPeerConnection(
    RtcPeerConnection self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcRemoteTrack(
    RtcRemoteTrack self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerH264Decoder(
    H264Decoder self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerH264Encoder(
    H264Encoder self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcDataChannel(
    RtcDataChannel self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcMediaSender(
    RtcMediaSender self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcPeerConnection(
    RtcPeerConnection self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcRemoteTrack(
    RtcRemoteTrack self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerH264Decoder(
    H264Decoder self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerH264Encoder(
    H264Encoder self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcDataChannel(
    RtcDataChannel self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcMediaSender(
    RtcMediaSender self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcPeerConnection(
    RtcPeerConnection self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcRemoteTrack(
    RtcRemoteTrack self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_data_channel_event_Sse(
    RustStreamSink<DataChannelEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_peer_connection_event_Sse(
    RustStreamSink<PeerConnectionEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_remote_rtp_packet_Sse(
    RustStreamSink<RemoteRtpPacket> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_decoded_video_frame(
    DecodedVideoFrame self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_rtc_config(
    RtcConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_data_channel_event(
    DataChannelEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_decoded_video_frame(
    DecodedVideoFrame self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_ice_connection_state(
    IceConnectionState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ice_gathering_state(
    IceGatheringState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ice_server(IceServer self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ice_server(
    List<IceServer> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_kind(MediaKind self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_decoded_video_frame(
    DecodedVideoFrame? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_peer_connection_event(
    PeerConnectionEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_peer_connection_state(
    PeerConnectionState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_remote_rtp_packet(
    RemoteRtpPacket self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rtc_config(RtcConfig self, SseSerializer serializer);

  @protected
  void sse_encode_signaling_state(
    SignalingState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerH264Decoder(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerH264Decoder(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerH264Decoder(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerH264Decoder(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerH264Encoder(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerH264Encoder(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerH264Encoder(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerH264Encoder(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcDataChannel(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcDataChannel(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcDataChannel(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcDataChannel(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcMediaSender(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcMediaSender(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcMediaSender(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcMediaSender(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcPeerConnection(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcPeerConnection(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcPeerConnection(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcPeerConnection(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcRemoteTrack(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcRemoteTrack(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcRemoteTrack(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcRemoteTrack(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerH264Decoder(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerH264Decoder(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerH264Encoder(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerH264Encoder(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcDataChannel(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcDataChannel(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcMediaSender(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcMediaSender(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcPeerConnection(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcPeerConnection(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcRemoteTrack(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRtcRemoteTrack(
    int ptr,
  );
}
