include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

linter:
  rules:
    unnecessary_await_in_return: true
    avoid_annotating_with_dynamic: true
    sort_child_properties_last: true
    unawaited_futures: true
    avoid_void_async: true
    prefer_final_locals: true
    always_declare_return_types: true
    prefer_final_in_for_each: true
    unnecessary_raw_strings: true
    flutter_style_todos: true
    use_raw_strings: true
    prefer_foreach: true
    sort_constructors_first: true
    directives_ordering: true
    prefer_relative_imports: true
