// Builds libopus (third_party/opus, vendored as a git submodule) via CMake,
// and registers the resulting shared library as the `package:opus/opus`
// code asset that lib/src/opus_bindings_generated.dart (generated by ffigen
// from opus.h) resolves against.
//
// Unlike the `dave` package, opus has no third-party dependencies (no
// vcpkg needed) - it's a small, self-contained CMake project, so this hook
// is a straightforward `cmake -B && cmake --build --target install`.
//
// Currently only macOS is implemented - see dave's hook/build.dart for the
// notes on adding other platforms; the same approach applies here (and is
// simpler, since there's no vcpkg triplet to pick).
import 'dart:io';

import 'package:code_assets/code_assets.dart';
import 'package:hooks/hooks.dart';
import 'package:logging/logging.dart';

final _log = Logger('opus.hook.build');

void main(List<String> args) async {
  Logger.root.level = Level.ALL;
  Logger.root.onRecord.listen((record) => print('[${record.level.name}] ${record.message}'));

  await build(args, (input, output) async {
    if (!input.config.buildCodeAssets) return;

    final libraryFile = await _buildOpus(input);

    output.assets.code.add(
      CodeAsset(
        package: input.packageName,
        name: 'opus',
        linkMode: DynamicLoadingBundled(),
        file: libraryFile,
      ),
    );

    output.dependencies.add(input.packageRoot.resolve('third_party/opus/'));
  });
}

Future<Uri> _buildOpus(BuildInput input) async {
  final code = input.config.code;
  final targetOS = code.targetOS;

  final opusDir = Directory.fromUri(input.packageRoot.resolve('third_party/opus/'));
  if (!opusDir.existsSync()) {
    throw StateError(
      'third_party/opus submodule not found at ${opusDir.path}. '
      'Run `git submodule update --init --recursive` in the opus package.',
    );
  }

  final buildDirUri = input.outputDirectory.resolve('opus_build/');
  final buildDir = Directory.fromUri(buildDirUri);
  final installDir = Directory.fromUri(buildDirUri.resolve('install/'));

  final Uri libraryFile;
  switch (targetOS) {
    case OS.macOS:
      libraryFile = await _buildForMacOS(
        opusDir: opusDir,
        buildDir: buildDir,
        installDir: installDir,
        architecture: code.targetArchitecture,
        deploymentTarget: code.macOS.targetVersion,
      );
    default:
      throw UnsupportedError(
        'opus: building libopus for $targetOS is not implemented yet '
        '(only macOS is wired up so far). See hook/build.dart.',
      );
  }

  if (!File.fromUri(libraryFile).existsSync()) {
    throw StateError('opus: expected libopus build output at $libraryFile but it does not exist');
  }
  return libraryFile;
}

Future<Uri> _buildForMacOS({
  required Directory opusDir,
  required Directory buildDir,
  required Directory installDir,
  required Architecture architecture,
  required int deploymentTarget,
}) async {
  final installedLibrary = File('${installDir.path}/lib/libopus.dylib');
  if (installedLibrary.existsSync()) {
    _log.info('opus: reusing existing build at ${installedLibrary.path}');
    return installedLibrary.uri;
  }

  await _run('cmake', [
    '-B', buildDir.path,
    '-DCMAKE_BUILD_TYPE=Release',
    '-DOPUS_BUILD_SHARED_LIBRARY=ON',
    '-DOPUS_BUILD_TESTING=OFF',
    '-DOPUS_BUILD_PROGRAMS=OFF',
    '-DCMAKE_INSTALL_PREFIX=${installDir.path}',
    '-DCMAKE_OSX_ARCHITECTURES=${architecture == Architecture.arm64 ? 'arm64' : 'x86_64'}',
    '-DCMAKE_OSX_DEPLOYMENT_TARGET=$deploymentTarget',
  ], workingDirectory: opusDir.path);

  await _run('cmake', [
    '--build', buildDir.path,
    '--target', 'install',
    '--config', 'Release',
  ], workingDirectory: opusDir.path);

  return installedLibrary.uri;
}

Future<void> _run(String executable, List<String> arguments, {required String workingDirectory}) async {
  _log.info('opus: running `$executable ${arguments.join(' ')}` in $workingDirectory');
  final process = await Process.start(
    executable,
    arguments,
    workingDirectory: workingDirectory,
    mode: ProcessStartMode.inheritStdio,
  );
  final exitCode = await process.exitCode;
  if (exitCode != 0) {
    throw ProcessException(executable, arguments, 'opus: build step failed (exit $exitCode)', exitCode);
  }
}
