// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyB5C1oSBsasLz7l_GeBWPHL6t5OiFgmciE',
//     appId: '1:653247688936:web:e8a3342796ba64bc05595d',
//     messagingSenderId: '653247688936',
//     projectId: 'bonfire-app-dev',
//     authDomain: 'bonfire-app-dev.firebaseapp.com',
//     storageBucket: 'bonfire-app-dev.firebasestorage.app',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAYW39Zp9d5BuUu3W6ky_3HpRQJ_kQO62c',
//     appId: '1:653247688936:android:d573298672d5315d05595d',
//     messagingSenderId: '653247688936',
//     projectId: 'bonfire-app-dev',
//     storageBucket: 'bonfire-app-dev.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCloHPM4mc8oFLZOKSxrUQnRRSIDr56hyo',
//     appId: '1:653247688936:ios:f00c28b74dc92e5805595d',
//     messagingSenderId: '653247688936',
//     projectId: 'bonfire-app-dev',
//     storageBucket: 'bonfire-app-dev.firebasestorage.app',
//     iosBundleId: 'com.example.bonfire',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCloHPM4mc8oFLZOKSxrUQnRRSIDr56hyo',
//     appId: '1:653247688936:ios:f00c28b74dc92e5805595d',
//     messagingSenderId: '653247688936',
//     projectId: 'bonfire-app-dev',
//     storageBucket: 'bonfire-app-dev.firebasestorage.app',
//     iosBundleId: 'com.example.bonfire',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyB5C1oSBsasLz7l_GeBWPHL6t5OiFgmciE',
//     appId: '1:653247688936:web:148adec6040260a205595d',
//     messagingSenderId: '653247688936',
//     projectId: 'bonfire-app-dev',
//     authDomain: 'bonfire-app-dev.firebaseapp.com',
//     storageBucket: 'bonfire-app-dev.firebasestorage.app',
//   );
// }
