// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'types.dart';

/// Enumerates cameras available to capture from on this device.
Future<List<CaptureDeviceInfo>> listCameras() =>
    RustLib.instance.api.crateApiCaptureListCameras();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CameraCaptureSession>>
abstract class CameraCaptureSession implements RustOpaqueInterface {
  /// `device_id` from [`list_cameras`], or `None` for the platform default.
  static CameraCaptureSession create({
    String? deviceId,
    required int width,
    required int height,
    required int fps,
    required int bitrateBps,
  }) => RustLib.instance.api.crateApiCaptureCameraCaptureSessionCreate(
    deviceId: deviceId,
    width: width,
    height: height,
    fps: fps,
    bitrateBps: bitrateBps,
  );

  Stream<EncodedVideoFrame> start();

  Future<void> stop();
}
