// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// One camera the current platform can capture from.
class CaptureDeviceInfo {
  /// Stable platform identifier - pass back to [`crate::api::capture::CameraCaptureSession::create`].
  final String id;
  final String name;

  const CaptureDeviceInfo({required this.id, required this.name});

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CaptureDeviceInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}

/// One encoded access unit (H264 Annex-B bytes - SPS+PPS+IDR-slice together
/// for a keyframe, just a slice for a delta frame) ready to hand to a DAVE
/// encryptor and RTP sender - see `flutter_webrtc_rs`'s
/// `RtcMediaSender::writePacketizedFrame`, which this is designed to feed
/// directly. This crate knows nothing about Discord, DAVE, or RTP - encoding
/// is where its responsibility ends.
class EncodedVideoFrame {
  final Uint8List data;
  final int width;
  final int height;
  final bool isKeyframe;

  /// Frame duration in microseconds, measured from the actual capture
  /// timestamps (not a nominal fixed value) - mirrors what the caller
  /// (`VoiceWebRtcRsSession`) already does for camera_macos frames today.
  final BigInt durationMicros;

  const EncodedVideoFrame({
    required this.data,
    required this.width,
    required this.height,
    required this.isKeyframe,
    required this.durationMicros,
  });

  @override
  int get hashCode =>
      data.hashCode ^
      width.hashCode ^
      height.hashCode ^
      isKeyframe.hashCode ^
      durationMicros.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncodedVideoFrame &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          width == other.width &&
          height == other.height &&
          isKeyframe == other.isKeyframe &&
          durationMicros == other.durationMicros;
}
