// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'types.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RtcDataChannel>>
abstract class RtcDataChannel implements RustOpaqueInterface {
  Future<void> close();

  /// Subscribes to this channel's lifecycle/message events. Each call spawns its own
  /// poll loop against the channel, so subscribe once per channel - a second
  /// subscription would race the first for each polled event rather than both
  /// seeing every event.
  Stream<DataChannelEvent> events();

  Future<String> label();

  /// Sends a binary message.
  Future<void> sendBinary({required List<int> data});

  /// Sends a UTF-8 text message.
  Future<void> sendText({required String text});
}
