// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'data_channel.dart';
import 'media.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `emit`, `fresh_id`, `new`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Handler`, `Shared`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `on_connection_state_change`, `on_data_channel`, `on_ice_candidate`, `on_ice_connection_state_change`, `on_ice_gathering_state_change`, `on_negotiation_needed`, `on_signaling_state_change`, `on_track`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RtcPeerConnection>>
abstract class RtcPeerConnection implements RustOpaqueInterface {
  /// `candidate_json` is a JSON-encoded `RTCIceCandidateInit`, as received from the
  /// remote peer's [`PeerConnectionEvent::IceCandidate`] over your signaling channel.
  Future<void> addIceCandidate({required String candidateJson});

  /// Adds a local media sender for `kind` (e.g. `MediaKind::Audio` for an
  /// Opus-encoded microphone track) and triggers renegotiation. `mime_type` should
  /// match one registered on the `MediaEngine` - see `MIME_TYPE_OPUS` etc. in
  /// `rtc::peer_connection::configuration::media_engine`; every default codec is
  /// already registered by [`create`], so passing e.g. `"audio/opus"` here works
  /// without any extra setup.
  /// `ssrc`: pass `None` to have one generated at random (the normal case);
  /// pass `Some(...)` when the remote server pre-assigned a specific SSRC
  /// this sender must use - e.g. Discord's voice gateway hands out a video
  /// SSRC in its Ready payload *before* any SDP is exchanged, and expects
  /// the eventual video sender to use exactly that value, not a random one
  /// webrtc-rs picked on its own.
  Future<RtcMediaSender> addMediaSender({
    required MediaKind kind,
    required String mimeType,
    int? ssrc,
  });

  Future<void> close();

  /// Creates a new connection and starts it gathering ICE candidates immediately
  /// (an implicit offer/answer role isn't chosen yet - call [`create_offer`] or
  /// feed it a remote offer via [`set_remote_description`] + [`create_answer`]).
  ///
  /// Call [`events`](Self::events) to subscribe to this connection's
  /// [`PeerConnectionEvent`]s - events fired before that call are buffered, not
  /// lost, so there's no race with early ICE candidates/state changes.
  static Future<RtcPeerConnection> create({required RtcConfig config}) =>
      RustLib.instance.api.crateApiPeerConnectionRtcPeerConnectionCreate(
        config: config,
      );

  /// Creates an SDP answer (call after `set_remote_description` with a remote
  /// offer), JSON-encoded.
  Future<String> createAnswer();

  /// Creates a local data channel (triggers renegotiation via `NegotiationNeeded`
  /// unless this is the very first one, negotiated in the initial offer).
  Future<RtcDataChannel> createDataChannel({required String label});

  /// Creates an SDP offer, JSON-encoded (an `RTCSessionDescription`).
  Future<String> createOffer();

  /// Subscribes to this connection's events, including any fired before this call
  /// (see [`create`](Self::create)). Call at most once - a second call gets a
  /// stream that never emits anything, since the internal buffer has already been
  /// handed to the first caller.
  Stream<PeerConnectionEvent> events();

  /// The current local description, if any has been set, JSON-encoded.
  Future<String?> localDescription();

  /// `description_json` is a JSON-encoded `RTCSessionDescription` (as produced by
  /// `create_offer`/`create_answer` on either this connection or the remote peer).
  Future<void> setLocalDescription({required String descriptionJson});

  Future<void> setRemoteDescription({required String descriptionJson});

  /// Fetches the handle for a data channel the remote peer created, previously
  /// announced via [`PeerConnectionEvent::DataChannel`].
  Future<RtcDataChannel> takeRemoteDataChannel({required String channelId});

  /// Fetches the handle for a remote media track, previously announced via
  /// [`PeerConnectionEvent::RemoteTrack`].
  Future<RtcRemoteTrack> takeRemoteTrack({required String trackId});
}
