// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

@freezed
sealed class DataChannelEvent with _$DataChannelEvent {
  const DataChannelEvent._();

  const factory DataChannelEvent.open() = DataChannelEvent_Open;
  const factory DataChannelEvent.message({
    required Uint8List data,
    required bool isText,
  }) = DataChannelEvent_Message;
  const factory DataChannelEvent.closing() = DataChannelEvent_Closing;
  const factory DataChannelEvent.closed() = DataChannelEvent_Closed;
  const factory DataChannelEvent.error() = DataChannelEvent_Error;

  /// Buffered-amount watermark events, kept only so `poll()`'s full event set is
  /// representable - most callers can ignore both.
  const factory DataChannelEvent.bufferedAmountLow() =
      DataChannelEvent_BufferedAmountLow;
  const factory DataChannelEvent.bufferedAmountHigh() =
      DataChannelEvent_BufferedAmountHigh;
}

enum IceConnectionState {
  new_,
  checking,
  connected,
  completed,
  disconnected,
  failed,
  closed,
}

enum IceGatheringState { new_, gathering, complete }

/// One ICE/STUN/TURN server, mirroring [`webrtc::peer_connection::RTCIceServer`].
class IceServer {
  final List<String> urls;
  final String username;
  final String credential;

  const IceServer({
    required this.urls,
    required this.username,
    required this.credential,
  });

  @override
  int get hashCode => urls.hashCode ^ username.hashCode ^ credential.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IceServer &&
          runtimeType == other.runtimeType &&
          urls == other.urls &&
          username == other.username &&
          credential == other.credential;
}

enum MediaKind { audio, video }

@freezed
sealed class PeerConnectionEvent with _$PeerConnectionEvent {
  const PeerConnectionEvent._();

  const factory PeerConnectionEvent.connectionStateChanged(
    PeerConnectionState field0,
  ) = PeerConnectionEvent_ConnectionStateChanged;
  const factory PeerConnectionEvent.iceGatheringStateChanged(
    IceGatheringState field0,
  ) = PeerConnectionEvent_IceGatheringStateChanged;
  const factory PeerConnectionEvent.iceConnectionStateChanged(
    IceConnectionState field0,
  ) = PeerConnectionEvent_IceConnectionStateChanged;
  const factory PeerConnectionEvent.signalingStateChanged(
    SignalingState field0,
  ) = PeerConnectionEvent_SignalingStateChanged;

  /// A local ICE candidate was gathered - its JSON (an `RTCIceCandidateInit`).
  /// Forward it to the remote peer over your own signaling channel. There is no
  /// separate "end of candidates" event: watch for `IceGatheringStateChanged`
  /// reaching `IceGatheringState::Complete` instead.
  const factory PeerConnectionEvent.iceCandidate({
    required String candidateJson,
  }) = PeerConnectionEvent_IceCandidate;

  /// The remote peer created a data channel in-band. Fetch a handle with
  /// `RtcPeerConnection::take_remote_data_channel(channel_id)`.
  const factory PeerConnectionEvent.dataChannel({required String channelId}) =
      PeerConnectionEvent_DataChannel;

  /// A remote media track became available. Fetch a handle with
  /// `RtcPeerConnection::take_remote_track(track_id)`.
  const factory PeerConnectionEvent.remoteTrack({
    required String trackId,
    required MediaKind kind,
    required String mimeType,
  }) = PeerConnectionEvent_RemoteTrack;

  /// The local description needs to be renegotiated (e.g. after `add_media_sender`).
  const factory PeerConnectionEvent.negotiationNeeded() =
      PeerConnectionEvent_NegotiationNeeded;
}

enum PeerConnectionState {
  new_,
  connecting,
  connected,
  disconnected,
  failed,
  closed,
}

/// One inbound RTP packet's payload for a subscribed remote track.
///
/// The payload is exactly the bytes the sender put on the wire for this packet - if
/// the caller is running DAVE (or any other frame-level scheme) on top, it is still
/// encrypted here. This layer never inspects payload contents; decrypt it, then feed
/// it to your decoder (Opus, VP8, ...) keyed off `sequence_number`/`timestamp` as
/// usual. Reassembly/reordering below the packet level (e.g. multi-packet video
/// frames) is not done by this layer - see the crate README.
class RemoteRtpPacket {
  final Uint8List payload;
  final int sequenceNumber;
  final int timestamp;
  final int ssrc;
  final bool marker;

  const RemoteRtpPacket({
    required this.payload,
    required this.sequenceNumber,
    required this.timestamp,
    required this.ssrc,
    required this.marker,
  });

  @override
  int get hashCode =>
      payload.hashCode ^
      sequenceNumber.hashCode ^
      timestamp.hashCode ^
      ssrc.hashCode ^
      marker.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteRtpPacket &&
          runtimeType == other.runtimeType &&
          payload == other.payload &&
          sequenceNumber == other.sequenceNumber &&
          timestamp == other.timestamp &&
          ssrc == other.ssrc &&
          marker == other.marker;
}

/// Configuration for [`crate::api::peer_connection::RtcPeerConnection::create`].
class RtcConfig {
  final List<IceServer> iceServers;

  /// Local `host:port` addresses to bind UDP sockets on and gather ICE host
  /// candidates from - `"0.0.0.0:0"` (bind an ephemeral port on every interface,
  /// the default) is almost always right for a real call. Override this to
  /// restrict which interfaces are used, or (the reason this is here rather than
  /// hardcoded) to force same-host loopback for testing: some sandboxed/
  /// containerized networks don't hairpin traffic a process sends to its own
  /// LAN-facing address back to itself, which reads as ICE connectivity checks
  /// hanging forever at `IceConnectionState.checking` even though both peers are
  /// on the same machine - binding both sides to `"127.0.0.1:0"` sidesteps that.
  final List<String> udpBindAddrs;

  const RtcConfig({required this.iceServers, required this.udpBindAddrs});

  static Future<RtcConfig> default_() =>
      RustLib.instance.api.crateApiTypesRtcConfigDefault();

  @override
  int get hashCode => iceServers.hashCode ^ udpBindAddrs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RtcConfig &&
          runtimeType == other.runtimeType &&
          iceServers == other.iceServers &&
          udpBindAddrs == other.udpBindAddrs;
}

enum SignalingState {
  stable,
  haveLocalOffer,
  haveRemoteOffer,
  haveLocalPranswer,
  haveRemotePranswer,
  closed,
}
