// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<H264Decoder>>
abstract class H264Decoder implements RustOpaqueInterface {
  static Future<H264Decoder> create() =>
      RustLib.instance.api.crateApiVideoCodecH264DecoderCreate();

  /// Feeds one depacketized H264 access unit's worth of Annex-B bytes in.
  /// openh264 buffers internally across calls (SPS/PPS, reference frames) and
  /// only returns `Some` once it has produced a displayable picture - most
  /// calls (e.g. one that only delivered parameter sets) return `None`, which
  /// is not an error.
  Future<DecodedVideoFrame?> decode({required List<int> data});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<H264Encoder>>
abstract class H264Encoder implements RustOpaqueInterface {
  /// `bitrate_bps` is a target, not a hard cap - openh264's rate control will
  /// exceed it somewhat on complex frames.
  ///
  /// Configures a periodic keyframe every 15 frames (~1s at this crate's
  /// nominal 15fps capture rate) - openh264 defaults to *never* emitting
  /// another IDR after the very first frame
  /// (`IntraFramePeriod::from_num_frames(0)`, its "disable periodic intra
  /// frames" default). Without this, losing or missing that one startup
  /// keyframe (e.g. because DAVE's MLS handshake hadn't finished yet, so
  /// the very first frames get dropped rather than sent - see the caller's
  /// send loop) means a receiver can never recover for the rest of the
  /// call: there's no RTCP PLI/FIR handling in this crate yet to request
  /// one on demand (see [`force_intra_frame`](Self::force_intra_frame) for
  /// forcing one manually once that lands), so a fixed interval is the
  /// only recovery mechanism available today. This matches what a known-
  /// working reference implementation
  /// (github.com/Discord-RE/Discord-video-stream) does explicitly via
  /// ffmpeg's `-force_key_frames expr:gte(t,n_forced*1)` (also every 1s).
  static Future<H264Encoder> create({required int bitrateBps}) => RustLib
      .instance
      .api
      .crateApiVideoCodecH264EncoderCreate(bitrateBps: bitrateBps);

  /// Encodes one frame from BGRA8 pixel data (row-major, no padding -
  /// `width * height * 4` bytes). This is the pixel format macOS/iOS camera
  /// capture (`AVCaptureVideoDataOutput` with `kCVPixelFormatType_32BGRA`,
  /// what most Flutter camera plugins hand out on those platforms) uses
  /// natively, so no format conversion is needed on the Dart side.
  ///
  /// Returns Annex-B bytes (one or more NAL units, start-code-prefixed) -
  /// openh264 may emit SPS/PPS NALs ahead of the slice NAL on keyframes, all
  /// concatenated in this one buffer; `write_encoded_frame` and the RTP H264
  /// payloader downstream handle that transparently.
  Future<Uint8List> encodeBgra8({
    required List<int> data,
    required int width,
    required int height,
  });

  /// As [`encode_bgra8`](Self::encode_bgra8), for RGBA8 sources instead (some
  /// non-Apple capture paths use this layout).
  Future<Uint8List> encodeRgba8({
    required List<int> data,
    required int width,
    required int height,
  });

  /// Forces the *next* `encode_bgra8`/`encode_rgba8` call to produce a
  /// fresh IDR keyframe, regardless of the periodic interval configured in
  /// [`create`](Self::create). For manually recovering a stream (e.g. once
  /// this crate reads inbound RTCP PLI/FIR and wants to react to it) -
  /// unused by anything in this crate today.
  Future<void> forceIntraFrame();
}

/// One decoded video frame, RGB8 (3 bytes/pixel, row-major, no padding).
class DecodedVideoFrame {
  final int width;
  final int height;
  final Uint8List rgb;

  const DecodedVideoFrame({
    required this.width,
    required this.height,
    required this.rgb,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode ^ rgb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecodedVideoFrame &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          rgb == other.rgb;
}
