// Builds Discord's libdave (third_party/libdave, vendored as a git
// submodule) via CMake + vcpkg, and registers the resulting shared library
// as the `package:dave/dave` code asset that lib/src/dave_bindings_generated.dart
// (generated by ffigen from libdave's own C API header) resolves against.
//
// This does NOT use `package:native_toolchain_c`'s `CBuilder` - libdave's own
// build is a full CMake project with heavy external dependencies (OpenSSL,
// nlohmann_json, MLSPP) resolved through vcpkg, which is well outside what
// CBuilder is meant for. Instead this shells out to `cmake` directly,
// mirroring third_party/libdave/cpp/Makefile's `shared` target (see that
// Makefile for the canonical/upstream-maintained flags - keep this in sync
// with it if it changes), and reports the built library as a precompiled
// code asset the same way the `code_assets` package's own docs describe for
// bundling precompiled native code.
//
// Currently only macOS is implemented. See _buildForTarget below for where
// to add iOS/Android/Linux/Windows support (each needs its own vcpkg triplet
// and, for iOS/Android, a chainloaded cross-compilation toolchain file).
import 'dart:io';

import 'package:code_assets/code_assets.dart';
import 'package:hooks/hooks.dart';
import 'package:logging/logging.dart';

final _log = Logger('dave.hook.build');

void main(List<String> args) async {
  Logger.root.level = Level.ALL;
  Logger.root.onRecord.listen((record) => print('[${record.level.name}] ${record.message}'));

  await build(args, (input, output) async {
    if (!input.config.buildCodeAssets) return;

    final libraryFile = await _buildLibdave(input);

    output.assets.code.add(
      CodeAsset(
        package: input.packageName,
        name: 'dave',
        linkMode: DynamicLoadingBundled(),
        file: libraryFile,
      ),
    );

    // The whole vendored libdave tree affects the build; if any of it
    // changes, re-run this hook rather than trusting a stale cache.
    output.dependencies.add(input.packageRoot.resolve('third_party/libdave/'));
  });
}

Future<Uri> _buildLibdave(BuildInput input) async {
  final code = input.config.code;
  final targetOS = code.targetOS;

  final cppDir = Directory.fromUri(
    input.packageRoot.resolve('third_party/libdave/cpp/'),
  );
  if (!cppDir.existsSync()) {
    throw StateError(
      'third_party/libdave submodule not found at ${cppDir.path}. '
      'Run `git submodule update --init --recursive` in the dave package.',
    );
  }

  final buildDirUri = input.outputDirectory.resolve('libdave_build/');
  final buildDir = Directory.fromUri(buildDirUri);
  final installDir = Directory.fromUri(buildDirUri.resolve('install/'));

  final Uri libraryFile;
  switch (targetOS) {
    case OS.macOS:
      libraryFile = await _buildForMacOS(
        cppDir: cppDir,
        buildDir: buildDir,
        installDir: installDir,
        architecture: code.targetArchitecture,
        deploymentTarget: code.macOS.targetVersion,
      );
    default:
      throw UnsupportedError(
        'dave: building libdave for $targetOS is not implemented yet '
        '(only macOS is wired up so far). See hook/build.dart.',
      );
  }

  if (!File.fromUri(libraryFile).existsSync()) {
    throw StateError('dave: expected libdave build output at $libraryFile but it does not exist');
  }
  return libraryFile;
}

Future<Uri> _buildForMacOS({
  required Directory cppDir,
  required Directory buildDir,
  required Directory installDir,
  required Architecture architecture,
  required int deploymentTarget,
}) async {
  final installedLibrary = File('${installDir.path}/lib/libdave.dylib');
  if (installedLibrary.existsSync()) {
    _log.info('dave: reusing existing build at ${installedLibrary.path}');
    return installedLibrary.uri;
  }

  final triplet = switch (architecture) {
    Architecture.arm64 => 'arm64-osx',
    Architecture.x64 => 'x64-osx',
    _ => throw UnsupportedError('dave: unsupported macOS architecture $architecture'),
  };

  // Mirrors third_party/libdave/cpp/Makefile's `shared` target (BUILD_TYPE
  // Release, BUILD_SHARED_LIBS=ON), plus the macOS-specific triplet/arch/
  // deployment-target flags CMake needs since we invoke cmake ourselves
  // rather than through that Makefile.
  await _run('cmake', [
    '-B', buildDir.path,
    '-DCMAKE_BUILD_TYPE=Release',
    '-DVCPKG_MANIFEST_DIR=vcpkg-alts/openssl_3',
    '-DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake',
    '-DVCPKG_TARGET_TRIPLET=$triplet',
    '-DBUILD_SHARED_LIBS=ON',
    '-DENABLE_SANITIZERS=OFF',
    '-DPERSISTENT_KEYS=OFF',
    '-DTESTING=OFF',
    '-DCMAKE_INSTALL_PREFIX=${installDir.path}',
    '-DCMAKE_OSX_ARCHITECTURES=${architecture == Architecture.arm64 ? 'arm64' : 'x86_64'}',
    '-DCMAKE_OSX_DEPLOYMENT_TARGET=$deploymentTarget',
  ], workingDirectory: cppDir.path);

  // libdave's CMakeLists.txt sets CMAKE_SKIP_INSTALL_ALL_DEPENDENCY ON, so
  // (unlike a typical CMake project) the `install` target does NOT build the
  // library first - build the `libdave` target explicitly before installing,
  // matching how the upstream Makefile is meant to be used (`make shared`
  // then `make install`, never `install` alone).
  await _run('cmake', [
    '--build', buildDir.path,
    '--target', 'libdave',
    '--config', 'Release',
  ], workingDirectory: cppDir.path);

  await _run('cmake', [
    '--build', buildDir.path,
    '--target', 'install',
    '--config', 'Release',
  ], workingDirectory: cppDir.path);

  return installedLibrary.uri;
}

Future<void> _run(String executable, List<String> arguments, {required String workingDirectory}) async {
  _log.info('dave: running `$executable ${arguments.join(' ')}` in $workingDirectory');
  final process = await Process.start(
    executable,
    arguments,
    workingDirectory: workingDirectory,
    mode: ProcessStartMode.inheritStdio,
  );
  final exitCode = await process.exitCode;
  if (exitCode != 0) {
    throw ProcessException(executable, arguments, 'dave: build step failed (exit $exitCode)', exitCode);
  }
}
