// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:dave/dave')
library;

import 'dart:ffi' as ffi;

/// @brief Returns the maximum protocol version supported by this library
/// @return Maximum supported protocol version number
@ffi.Native<ffi.Uint16 Function()>()
external int daveMaxSupportedProtocolVersion();

/// @brief Frees memory allocated by the DAVE library
///
/// Use this function to free any byte arrays or buffers allocated by DAVE API
/// functions.
///
/// @param ptr Pointer to memory previously allocated by a DAVE API function.
/// If NULL, this function does nothing.
///
/// @note This function should be used to free output byte arrays from functions
/// like daveSessionGetLastEpochAuthenticator, daveSessionGetMarshalledKeyPackage,
/// daveCommitResultGetRosterMemberIds, etc. Do NOT use this to destroy handles;
/// use the corresponding *Destroy functions instead.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void daveFree(ffi.Pointer<ffi.Void> ptr);

/// @brief Creates a new DAVE session
/// @param context Currently unused platform-specific context pointer (can be NULL)
/// @param authSessionId String used to manage persistent key lifetimes (can be NULL)
/// @param callback Callback invoked on MLS failures
/// @param userData User data pointer passed to the callback
/// @return New session handle, or NULL on failure. Must be destroyed with daveSessionDestroy()
@ffi.Native<
  DAVESessionHandle Function(
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<ffi.Char>,
    DAVEMLSFailureCallback,
    ffi.Pointer<ffi.Void>,
  )
>()
external DAVESessionHandle daveSessionCreate(
  ffi.Pointer<ffi.Void> context,
  ffi.Pointer<ffi.Char> authSessionId,
  DAVEMLSFailureCallback callback,
  ffi.Pointer<ffi.Void> userData,
);

/// @brief Destroys a session and frees associated resources
/// @param session Session handle to destroy
@ffi.Native<ffi.Void Function(DAVESessionHandle)>()
external void daveSessionDestroy(DAVESessionHandle session);

/// @brief Initializes a session with protocol version and group information
/// @param session Session handle
/// @param version Protocol version to use
/// @param groupId Group identifier common to all users in the group
/// @param selfUserId User ID of the local user
@ffi.Native<
  ffi.Void Function(
    DAVESessionHandle,
    ffi.Uint16,
    ffi.Uint64,
    ffi.Pointer<ffi.Char>,
  )
>()
external void daveSessionInit(
  DAVESessionHandle session,
  int version,
  int groupId,
  ffi.Pointer<ffi.Char> selfUserId,
);

/// @brief Resets the session state
/// @param session Session handle
@ffi.Native<ffi.Void Function(DAVESessionHandle)>()
external void daveSessionReset(DAVESessionHandle session);

/// @brief Sets the protocol version for the session
/// @param session Session handle
/// @param version Protocol version to set
@ffi.Native<ffi.Void Function(DAVESessionHandle, ffi.Uint16)>()
external void daveSessionSetProtocolVersion(
  DAVESessionHandle session,
  int version,
);

/// @brief Gets the current protocol version of the session
/// @param session Session handle
/// @return Current protocol version
@ffi.Native<ffi.Uint16 Function(DAVESessionHandle)>()
external int daveSessionGetProtocolVersion(DAVESessionHandle session);

/// @brief Retrieves the authenticator from the last MLS epoch
/// @param session Session handle
/// @param[out] authenticator Output pointer to authenticator bytes (caller must free with daveFree)
/// @param[out] length Output pointer to authenticator length
@ffi.Native<
  ffi.Void Function(
    DAVESessionHandle,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Pointer<ffi.Size>,
  )
>()
external void daveSessionGetLastEpochAuthenticator(
  DAVESessionHandle session,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> authenticator,
  ffi.Pointer<ffi.Size> length,
);

/// @brief Sets the external sender credentials for the session
/// @param session Session handle
/// @param externalSender External sender credential bytes
/// @param length Length of external sender data
@ffi.Native<
  ffi.Void Function(DAVESessionHandle, ffi.Pointer<ffi.Uint8>, ffi.Size)
>()
external void daveSessionSetExternalSender(
  DAVESessionHandle session,
  ffi.Pointer<ffi.Uint8> externalSender,
  int length,
);

/// @brief Processes MLS proposals and generates commit/welcome messages
/// @param session Session handle
/// @param proposals Serialized proposal bytes
/// @param length Length of proposals
/// @param recognizedUserIds Array of recognized user ID strings
/// @param recognizedUserIdsLength Number of recognized user IDs
/// @param[out] commitWelcomeBytes Output buffer to commit/welcome message bytes (caller must free with daveFree)
/// @param[out] commitWelcomeBytesLength Output length of the commit/welcome message
@ffi.Native<
  ffi.Void Function(
    DAVESessionHandle,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Size,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Pointer<ffi.Size>,
  )
>()
external void daveSessionProcessProposals(
  DAVESessionHandle session,
  ffi.Pointer<ffi.Uint8> proposals,
  int length,
  ffi.Pointer<ffi.Pointer<ffi.Char>> recognizedUserIds,
  int recognizedUserIdsLength,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> commitWelcomeBytes,
  ffi.Pointer<ffi.Size> commitWelcomeBytesLength,
);

/// @brief Processes an incoming MLS commit message
/// @param session Session handle
/// @param commit Serialized commit message bytes
/// @param length Length of commit message
/// @return Commit result handle. Must be destroyed with daveCommitResultDestroy()
@ffi.Native<
  DAVECommitResultHandle Function(
    DAVESessionHandle,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
  )
>()
external DAVECommitResultHandle daveSessionProcessCommit(
  DAVESessionHandle session,
  ffi.Pointer<ffi.Uint8> commit,
  int length,
);

/// @brief Processes an incoming MLS welcome message to join a group
/// @param session Session handle
/// @param welcome Serialized welcome message bytes
/// @param length Length of welcome message
/// @param recognizedUserIds Array of recognized user ID strings
/// @param recognizedUserIdsLength Number of recognized user IDs
/// @return Welcome result handle. Must be destroyed with daveWelcomeResultDestroy()
@ffi.Native<
  DAVEWelcomeResultHandle Function(
    DAVESessionHandle,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Size,
  )
>()
external DAVEWelcomeResultHandle daveSessionProcessWelcome(
  DAVESessionHandle session,
  ffi.Pointer<ffi.Uint8> welcome,
  int length,
  ffi.Pointer<ffi.Pointer<ffi.Char>> recognizedUserIds,
  int recognizedUserIdsLength,
);

/// @brief Gets the marshalled MLS key package for this session
/// @param session Session handle
/// @param[out] keyPackage Output buffer to key package bytes (caller must free with daveFree)
/// @param[out] length Output length of the key package
@ffi.Native<
  ffi.Void Function(
    DAVESessionHandle,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Pointer<ffi.Size>,
  )
>()
external void daveSessionGetMarshalledKeyPackage(
  DAVESessionHandle session,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> keyPackage,
  ffi.Pointer<ffi.Size> length,
);

/// @brief Gets a key ratchet for a specific user in the session
/// @param session Session handle
/// @param userId User ID to get key ratchet for
/// @return Key ratchet handle. Must be destroyed with daveKeyRatchetDestroy()
@ffi.Native<
  DAVEKeyRatchetHandle Function(DAVESessionHandle, ffi.Pointer<ffi.Char>)
>()
external DAVEKeyRatchetHandle daveSessionGetKeyRatchet(
  DAVESessionHandle session,
  ffi.Pointer<ffi.Char> userId,
);

/// @brief Computes a pairwise fingerprint for identity verification with another user
/// @param session Session handle
/// @param version Protocol version currently in use
/// @param userId User ID of the remote user to compute the fingerprint for
/// @param callback Callback to receive the fingerprint
/// @param userData User data passed to callback
@ffi.Native<
  ffi.Void Function(
    DAVESessionHandle,
    ffi.Uint16,
    ffi.Pointer<ffi.Char>,
    DAVEPairwiseFingerprintCallback,
    ffi.Pointer<ffi.Void>,
  )
>()
external void daveSessionGetPairwiseFingerprint(
  DAVESessionHandle session,
  int version,
  ffi.Pointer<ffi.Char> userId,
  DAVEPairwiseFingerprintCallback callback,
  ffi.Pointer<ffi.Void> userData,
);

/// @brief Destroys a key ratchet and frees associated resources
/// @param keyRatchet Key ratchet handle to destroy
@ffi.Native<ffi.Void Function(DAVEKeyRatchetHandle)>()
external void daveKeyRatchetDestroy(DAVEKeyRatchetHandle keyRatchet);

/// @brief Checks if processing the commit failed
/// @param commitResultHandle Commit result handle
/// @return true if commit processing failed
@ffi.Native<ffi.Bool Function(DAVECommitResultHandle)>()
external bool daveCommitResultIsFailed(
  DAVECommitResultHandle commitResultHandle,
);

/// @brief Checks if the commit should be ignored
/// @param commitResultHandle Commit result handle
/// @return true if commit should be ignored
@ffi.Native<ffi.Bool Function(DAVECommitResultHandle)>()
external bool daveCommitResultIsIgnored(
  DAVECommitResultHandle commitResultHandle,
);

/// @brief Gets the list of member IDs in the roster after the commit
/// @param commitResultHandle Commit result handle
/// @param[out] rosterIds Output buffer to array of roster member IDs (caller must free with daveFree)
/// @param[out] rosterIdsLength Output length of the roster member IDs array
@ffi.Native<
  ffi.Void Function(
    DAVECommitResultHandle,
    ffi.Pointer<ffi.Pointer<ffi.Uint64>>,
    ffi.Pointer<ffi.Size>,
  )
>()
external void daveCommitResultGetRosterMemberIds(
  DAVECommitResultHandle commitResultHandle,
  ffi.Pointer<ffi.Pointer<ffi.Uint64>> rosterIds,
  ffi.Pointer<ffi.Size> rosterIdsLength,
);

/// @brief Gets the signature for a specific roster member
/// @param commitResultHandle Commit result handle
/// @param rosterId Roster member ID
/// @param[out] signature Output buffer to signature bytes (caller must free with daveFree)
/// @param[out] signatureLength Output length of the signature
@ffi.Native<
  ffi.Void Function(
    DAVECommitResultHandle,
    ffi.Uint64,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Pointer<ffi.Size>,
  )
>()
external void daveCommitResultGetRosterMemberSignature(
  DAVECommitResultHandle commitResultHandle,
  int rosterId,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> signature,
  ffi.Pointer<ffi.Size> signatureLength,
);

/// @brief Destroys a commit result and frees associated resources
/// @param commitResultHandle Commit result handle to destroy
@ffi.Native<ffi.Void Function(DAVECommitResultHandle)>()
external void daveCommitResultDestroy(
  DAVECommitResultHandle commitResultHandle,
);

/// @brief Gets the list of member IDs in the roster from the welcome message
/// @param welcomeResultHandle Welcome result handle
/// @param[out] rosterIds Output buffer to array of roster member IDs (caller must free with daveFree)
/// @param[out] rosterIdsLength Output length of the roster member IDs array
@ffi.Native<
  ffi.Void Function(
    DAVEWelcomeResultHandle,
    ffi.Pointer<ffi.Pointer<ffi.Uint64>>,
    ffi.Pointer<ffi.Size>,
  )
>()
external void daveWelcomeResultGetRosterMemberIds(
  DAVEWelcomeResultHandle welcomeResultHandle,
  ffi.Pointer<ffi.Pointer<ffi.Uint64>> rosterIds,
  ffi.Pointer<ffi.Size> rosterIdsLength,
);

/// @brief Gets the signature for a specific roster member
/// @param welcomeResultHandle Welcome result handle
/// @param rosterId Roster member ID
/// @param[out] signature Output buffer to signature bytes (caller must free with daveFree)
/// @param[out] signatureLength Output length of the signature
@ffi.Native<
  ffi.Void Function(
    DAVEWelcomeResultHandle,
    ffi.Uint64,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Pointer<ffi.Size>,
  )
>()
external void daveWelcomeResultGetRosterMemberSignature(
  DAVEWelcomeResultHandle welcomeResultHandle,
  int rosterId,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> signature,
  ffi.Pointer<ffi.Size> signatureLength,
);

/// @brief Destroys a welcome result and frees associated resources
/// @param welcomeResultHandle Welcome result handle to destroy
@ffi.Native<ffi.Void Function(DAVEWelcomeResultHandle)>()
external void daveWelcomeResultDestroy(
  DAVEWelcomeResultHandle welcomeResultHandle,
);

/// @brief Creates a new media frame encryptor
/// @return New encryptor handle. Must be destroyed with daveEncryptorDestroy()
@ffi.Native<DAVEEncryptorHandle Function()>()
external DAVEEncryptorHandle daveEncryptorCreate();

/// @brief Destroys an encryptor and frees associated resources
/// @param encryptor Encryptor handle to destroy
@ffi.Native<ffi.Void Function(DAVEEncryptorHandle)>()
external void daveEncryptorDestroy(DAVEEncryptorHandle encryptor);

/// @brief Sets the key ratchet for encryption
/// @param encryptor Encryptor handle
/// @param keyRatchet Key ratchet to use for encryption (does *not* take ownership)
@ffi.Native<ffi.Void Function(DAVEEncryptorHandle, DAVEKeyRatchetHandle)>()
external void daveEncryptorSetKeyRatchet(
  DAVEEncryptorHandle encryptor,
  DAVEKeyRatchetHandle keyRatchet,
);

/// @brief Enables or disables passthrough mode (frames pass through unencrypted)
/// @param encryptor Encryptor handle
/// @param passthroughMode true to enable passthrough, false to encrypt
@ffi.Native<ffi.Void Function(DAVEEncryptorHandle, ffi.Bool)>()
external void daveEncryptorSetPassthroughMode(
  DAVEEncryptorHandle encryptor,
  bool passthroughMode,
);

/// @brief Associates an SSRC (Synchronization Source) with a specific codec
/// @param encryptor Encryptor handle
/// @param ssrc SSRC identifier
/// @param codecType Codec type for this SSRC
@ffi.Native<
  ffi.Void Function(DAVEEncryptorHandle, ffi.Uint32, ffi.UnsignedInt)
>(symbol: 'daveEncryptorAssignSsrcToCodec')
external void _daveEncryptorAssignSsrcToCodec(
  DAVEEncryptorHandle encryptor,
  int ssrc,
  int codecType,
);

void daveEncryptorAssignSsrcToCodec(
  DAVEEncryptorHandle encryptor,
  int ssrc,
  DAVECodec codecType,
) => _daveEncryptorAssignSsrcToCodec(encryptor, ssrc, codecType.value);

/// @brief Gets the current protocol version used by the encryptor
/// @param encryptor Encryptor handle
/// @return Protocol version number
@ffi.Native<ffi.Uint16 Function(DAVEEncryptorHandle)>()
external int daveEncryptorGetProtocolVersion(DAVEEncryptorHandle encryptor);

/// @brief Calculates the maximum ciphertext size for a given plaintext frame size
/// @param encryptor Encryptor handle
/// @param mediaType Media type (audio or video)
/// @param frameSize Size of plaintext frame in bytes
/// @return Maximum possible ciphertext size in bytes
@ffi.Native<ffi.Size Function(DAVEEncryptorHandle, ffi.UnsignedInt, ffi.Size)>(
  symbol: 'daveEncryptorGetMaxCiphertextByteSize',
)
external int _daveEncryptorGetMaxCiphertextByteSize(
  DAVEEncryptorHandle encryptor,
  int mediaType,
  int frameSize,
);

int daveEncryptorGetMaxCiphertextByteSize(
  DAVEEncryptorHandle encryptor,
  DAVEMediaType mediaType,
  int frameSize,
) => _daveEncryptorGetMaxCiphertextByteSize(
  encryptor,
  mediaType.value,
  frameSize,
);

/// @brief Checks if the encryptor has a key ratchet
/// @param encryptor Encryptor handle
/// @return true if has key ratchet, false otherwise
@ffi.Native<ffi.Bool Function(DAVEEncryptorHandle)>()
external bool daveEncryptorHasKeyRatchet(DAVEEncryptorHandle encryptor);

/// @brief Checks if the encryptor is in passthrough mode
/// @param encryptor Encryptor handle
/// @return true if in passthrough mode, false otherwise
@ffi.Native<ffi.Bool Function(DAVEEncryptorHandle)>()
external bool daveEncryptorIsPassthroughMode(DAVEEncryptorHandle encryptor);

/// @brief Encrypts a media frame
/// @param encryptor Encryptor handle
/// @param mediaType Media type (audio or video)
/// @param ssrc SSRC of the stream
/// @param frame Pointer to plaintext frame data
/// @param frameLength Length of plaintext frame
/// @param[out] encryptedFrame Pointer to the output buffer the encrypted frame will be written to
/// @param encryptedFrameCapacity Capacity of the output buffer
/// @param[out] bytesWritten Number of bytes written to the output buffer
/// @return Result code indicating success or failure
@ffi.Native<
  ffi.UnsignedInt Function(
    DAVEEncryptorHandle,
    ffi.UnsignedInt,
    ffi.Uint32,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(symbol: 'daveEncryptorEncrypt')
external int _daveEncryptorEncrypt(
  DAVEEncryptorHandle encryptor,
  int mediaType,
  int ssrc,
  ffi.Pointer<ffi.Uint8> frame,
  int frameLength,
  ffi.Pointer<ffi.Uint8> encryptedFrame,
  int encryptedFrameCapacity,
  ffi.Pointer<ffi.Size> bytesWritten,
);

DAVEEncryptorResultCode daveEncryptorEncrypt(
  DAVEEncryptorHandle encryptor,
  DAVEMediaType mediaType,
  int ssrc,
  ffi.Pointer<ffi.Uint8> frame,
  int frameLength,
  ffi.Pointer<ffi.Uint8> encryptedFrame,
  int encryptedFrameCapacity,
  ffi.Pointer<ffi.Size> bytesWritten,
) => DAVEEncryptorResultCode.fromValue(
  _daveEncryptorEncrypt(
    encryptor,
    mediaType.value,
    ssrc,
    frame,
    frameLength,
    encryptedFrame,
    encryptedFrameCapacity,
    bytesWritten,
  ),
);

/// @brief Sets a callback to be notified when the protocol version changes
/// @param encryptor Encryptor handle
/// @param callback Callback function
/// @param userData User data passed to callback
@ffi.Native<
  ffi.Void Function(
    DAVEEncryptorHandle,
    DAVEEncryptorProtocolVersionChangedCallback,
    ffi.Pointer<ffi.Void>,
  )
>()
external void daveEncryptorSetProtocolVersionChangedCallback(
  DAVEEncryptorHandle encryptor,
  DAVEEncryptorProtocolVersionChangedCallback callback,
  ffi.Pointer<ffi.Void> userData,
);

/// @brief Gets encryption statistics
/// @param encryptor Encryptor handle
/// @param mediaType Media type (audio or video)
/// @param[out] stats Pointer to the stats structure to be filled
@ffi.Native<
  ffi.Void Function(
    DAVEEncryptorHandle,
    ffi.UnsignedInt,
    ffi.Pointer<DAVEEncryptorStats>,
  )
>(symbol: 'daveEncryptorGetStats')
external void _daveEncryptorGetStats(
  DAVEEncryptorHandle encryptor,
  int mediaType,
  ffi.Pointer<DAVEEncryptorStats> stats,
);

void daveEncryptorGetStats(
  DAVEEncryptorHandle encryptor,
  DAVEMediaType mediaType,
  ffi.Pointer<DAVEEncryptorStats> stats,
) => _daveEncryptorGetStats(encryptor, mediaType.value, stats);

/// @brief Creates a new media frame decryptor
/// @return New decryptor handle. Must be destroyed with daveDecryptorDestroy()
@ffi.Native<DAVEDecryptorHandle Function()>()
external DAVEDecryptorHandle daveDecryptorCreate();

/// @brief Destroys a decryptor and frees associated resources
/// @param decryptor Decryptor handle to destroy
@ffi.Native<ffi.Void Function(DAVEDecryptorHandle)>()
external void daveDecryptorDestroy(DAVEDecryptorHandle decryptor);

/// @brief Transitions the decryptor to use a new key ratchet
/// @param decryptor Decryptor handle
/// @param keyRatchet New key ratchet to transition to (does *not* take ownership)
@ffi.Native<ffi.Void Function(DAVEDecryptorHandle, DAVEKeyRatchetHandle)>()
external void daveDecryptorTransitionToKeyRatchet(
  DAVEDecryptorHandle decryptor,
  DAVEKeyRatchetHandle keyRatchet,
);

/// @brief Transitions to or from passthrough mode
/// @param decryptor Decryptor handle
/// @param passthroughMode true to enable passthrough, false to decrypt
@ffi.Native<ffi.Void Function(DAVEDecryptorHandle, ffi.Bool)>()
external void daveDecryptorTransitionToPassthroughMode(
  DAVEDecryptorHandle decryptor,
  bool passthroughMode,
);

/// @brief Decrypts an encrypted media frame
/// @param decryptor Decryptor handle
/// @param mediaType Media type (audio or video)
/// @param encryptedFrame Pointer to the encrypted frame data
/// @param encryptedFrameLength Length of the encrypted frame
/// @param[out] frame Pointer to the output buffer the decrypted frame will be written to
/// @param frameCapacity Capacity of the output buffer
/// @param[out] bytesWritten Number of bytes written to the output buffer
/// @return Result code indicating success or failure
@ffi.Native<
  ffi.UnsignedInt Function(
    DAVEDecryptorHandle,
    ffi.UnsignedInt,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>(symbol: 'daveDecryptorDecrypt')
external int _daveDecryptorDecrypt(
  DAVEDecryptorHandle decryptor,
  int mediaType,
  ffi.Pointer<ffi.Uint8> encryptedFrame,
  int encryptedFrameLength,
  ffi.Pointer<ffi.Uint8> frame,
  int frameCapacity,
  ffi.Pointer<ffi.Size> bytesWritten,
);

DAVEDecryptorResultCode daveDecryptorDecrypt(
  DAVEDecryptorHandle decryptor,
  DAVEMediaType mediaType,
  ffi.Pointer<ffi.Uint8> encryptedFrame,
  int encryptedFrameLength,
  ffi.Pointer<ffi.Uint8> frame,
  int frameCapacity,
  ffi.Pointer<ffi.Size> bytesWritten,
) => DAVEDecryptorResultCode.fromValue(
  _daveDecryptorDecrypt(
    decryptor,
    mediaType.value,
    encryptedFrame,
    encryptedFrameLength,
    frame,
    frameCapacity,
    bytesWritten,
  ),
);

/// @brief Calculates the maximum plaintext size for a given ciphertext frame size
/// @param decryptor Decryptor handle
/// @param mediaType Media type (audio or video)
/// @param encryptedFrameSize Size of encrypted frame in bytes
/// @return Maximum possible plaintext size in bytes
@ffi.Native<ffi.Size Function(DAVEDecryptorHandle, ffi.UnsignedInt, ffi.Size)>(
  symbol: 'daveDecryptorGetMaxPlaintextByteSize',
)
external int _daveDecryptorGetMaxPlaintextByteSize(
  DAVEDecryptorHandle decryptor,
  int mediaType,
  int encryptedFrameSize,
);

int daveDecryptorGetMaxPlaintextByteSize(
  DAVEDecryptorHandle decryptor,
  DAVEMediaType mediaType,
  int encryptedFrameSize,
) => _daveDecryptorGetMaxPlaintextByteSize(
  decryptor,
  mediaType.value,
  encryptedFrameSize,
);

/// @brief Gets decryption statistics
/// @param decryptor Decryptor handle
/// @param mediaType Media type (audio or video)
/// @param[out] stats Pointer to the stats structure to be filled
@ffi.Native<
  ffi.Void Function(
    DAVEDecryptorHandle,
    ffi.UnsignedInt,
    ffi.Pointer<DAVEDecryptorStats>,
  )
>(symbol: 'daveDecryptorGetStats')
external void _daveDecryptorGetStats(
  DAVEDecryptorHandle decryptor,
  int mediaType,
  ffi.Pointer<DAVEDecryptorStats> stats,
);

void daveDecryptorGetStats(
  DAVEDecryptorHandle decryptor,
  DAVEMediaType mediaType,
  ffi.Pointer<DAVEDecryptorStats> stats,
) => _daveDecryptorGetStats(decryptor, mediaType.value, stats);

/// @brief Sets a global callback for receiving log messages from the library
/// @param callback Log sink callback function
@ffi.Native<ffi.Void Function(DAVELogSinkCallback)>()
external void daveSetLogSinkCallback(DAVELogSinkCallback callback);

final class DAVESessionHandle_s extends ffi.Opaque {}

/// @brief DAVE session handle for managing group encryption state
typedef DAVESessionHandle = ffi.Pointer<DAVESessionHandle_s>;

final class DAVECommitResultHandle_s extends ffi.Opaque {}

/// @brief Result handle from processing an MLS commit message
typedef DAVECommitResultHandle = ffi.Pointer<DAVECommitResultHandle_s>;

final class DAVEWelcomeResultHandle_s extends ffi.Opaque {}

/// @brief Result handle from processing an MLS welcome message
typedef DAVEWelcomeResultHandle = ffi.Pointer<DAVEWelcomeResultHandle_s>;

final class DAVEKeyRatchetHandle_s extends ffi.Opaque {}

/// @brief Key ratchet handle for deriving encryption keys
typedef DAVEKeyRatchetHandle = ffi.Pointer<DAVEKeyRatchetHandle_s>;

final class DAVEEncryptorHandle_s extends ffi.Opaque {}

/// @brief Media frame encryptor handle
typedef DAVEEncryptorHandle = ffi.Pointer<DAVEEncryptorHandle_s>;

final class DAVEDecryptorHandle_s extends ffi.Opaque {}

/// @brief Media frame decryptor handle
typedef DAVEDecryptorHandle = ffi.Pointer<DAVEDecryptorHandle_s>;

/// @brief Supported media codecs for encryption
enum DAVECodec {
  /// < Unknown or unspecified codec
  DAVE_CODEC_UNKNOWN(0),

  /// < Opus audio codec
  DAVE_CODEC_OPUS(1),

  /// < VP8 video codec
  DAVE_CODEC_VP8(2),

  /// < VP9 video codec
  DAVE_CODEC_VP9(3),

  /// < H.264/AVC video codec
  DAVE_CODEC_H264(4),

  /// < H.265/HEVC video codec
  DAVE_CODEC_H265(5),

  /// < AV1 video codec
  DAVE_CODEC_AV1(6);

  final int value;
  const DAVECodec(this.value);

  static DAVECodec fromValue(int value) => switch (value) {
    0 => DAVE_CODEC_UNKNOWN,
    1 => DAVE_CODEC_OPUS,
    2 => DAVE_CODEC_VP8,
    3 => DAVE_CODEC_VP9,
    4 => DAVE_CODEC_H264,
    5 => DAVE_CODEC_H265,
    6 => DAVE_CODEC_AV1,
    _ => throw ArgumentError('Unknown value for DAVECodec: $value'),
  };
}

/// @brief Media stream type classification
enum DAVEMediaType {
  /// < Audio stream
  DAVE_MEDIA_TYPE_AUDIO(0),

  /// < Video stream
  DAVE_MEDIA_TYPE_VIDEO(1);

  final int value;
  const DAVEMediaType(this.value);

  static DAVEMediaType fromValue(int value) => switch (value) {
    0 => DAVE_MEDIA_TYPE_AUDIO,
    1 => DAVE_MEDIA_TYPE_VIDEO,
    _ => throw ArgumentError('Unknown value for DAVEMediaType: $value'),
  };
}

/// @brief Result codes returned by encryption operations
enum DAVEEncryptorResultCode {
  /// < Encryption succeeded
  DAVE_ENCRYPTOR_RESULT_CODE_SUCCESS(0),

  /// < Encryption failed
  DAVE_ENCRYPTOR_RESULT_CODE_ENCRYPTION_FAILURE(1),

  /// < No key ratchet available
  DAVE_ENCRYPTOR_RESULT_CODE_MISSING_KEY_RATCHET(2),

  /// < Missing cryptographic context
  DAVE_ENCRYPTOR_RESULT_CODE_MISSING_CRYPTOR(3),

  /// < Too many attempts to encrypt the frame failed
  DAVE_ENCRYPTOR_RESULT_CODE_TOO_MANY_ATTEMPTS(4);

  final int value;
  const DAVEEncryptorResultCode(this.value);

  static DAVEEncryptorResultCode fromValue(int value) => switch (value) {
    0 => DAVE_ENCRYPTOR_RESULT_CODE_SUCCESS,
    1 => DAVE_ENCRYPTOR_RESULT_CODE_ENCRYPTION_FAILURE,
    2 => DAVE_ENCRYPTOR_RESULT_CODE_MISSING_KEY_RATCHET,
    3 => DAVE_ENCRYPTOR_RESULT_CODE_MISSING_CRYPTOR,
    4 => DAVE_ENCRYPTOR_RESULT_CODE_TOO_MANY_ATTEMPTS,
    _ => throw ArgumentError(
      'Unknown value for DAVEEncryptorResultCode: $value',
    ),
  };
}

/// @brief Result codes returned by decryption operations
enum DAVEDecryptorResultCode {
  /// < Decryption succeeded
  DAVE_DECRYPTOR_RESULT_CODE_SUCCESS(0),

  /// < Decryption failed
  DAVE_DECRYPTOR_RESULT_CODE_DECRYPTION_FAILURE(1),

  /// < No key ratchet available
  DAVE_DECRYPTOR_RESULT_CODE_MISSING_KEY_RATCHET(2),

  /// < Invalid nonce in encrypted frame
  DAVE_DECRYPTOR_RESULT_CODE_INVALID_NONCE(3),

  /// < Missing cryptographic context
  DAVE_DECRYPTOR_RESULT_CODE_MISSING_CRYPTOR(4);

  final int value;
  const DAVEDecryptorResultCode(this.value);

  static DAVEDecryptorResultCode fromValue(int value) => switch (value) {
    0 => DAVE_DECRYPTOR_RESULT_CODE_SUCCESS,
    1 => DAVE_DECRYPTOR_RESULT_CODE_DECRYPTION_FAILURE,
    2 => DAVE_DECRYPTOR_RESULT_CODE_MISSING_KEY_RATCHET,
    3 => DAVE_DECRYPTOR_RESULT_CODE_INVALID_NONCE,
    4 => DAVE_DECRYPTOR_RESULT_CODE_MISSING_CRYPTOR,
    _ => throw ArgumentError(
      'Unknown value for DAVEDecryptorResultCode: $value',
    ),
  };
}

/// @brief Log message severity levels
enum DAVELoggingSeverity {
  /// < Verbose debug information
  DAVE_LOGGING_SEVERITY_VERBOSE(0),

  /// < Informational messages
  DAVE_LOGGING_SEVERITY_INFO(1),

  /// < Warning messages
  DAVE_LOGGING_SEVERITY_WARNING(2),

  /// < Error messages
  DAVE_LOGGING_SEVERITY_ERROR(3),

  /// < Messages to be ignored
  DAVE_LOGGING_SEVERITY_NONE(4);

  final int value;
  const DAVELoggingSeverity(this.value);

  static DAVELoggingSeverity fromValue(int value) => switch (value) {
    0 => DAVE_LOGGING_SEVERITY_VERBOSE,
    1 => DAVE_LOGGING_SEVERITY_INFO,
    2 => DAVE_LOGGING_SEVERITY_WARNING,
    3 => DAVE_LOGGING_SEVERITY_ERROR,
    4 => DAVE_LOGGING_SEVERITY_NONE,
    _ => throw ArgumentError('Unknown value for DAVELoggingSeverity: $value'),
  };
}

typedef DAVEMLSFailureCallbackFunction = ffi.Void Function(
  ffi.Pointer<ffi.Char> source,
  ffi.Pointer<ffi.Char> reason,
  ffi.Pointer<ffi.Void> userData,
);
typedef DartDAVEMLSFailureCallbackFunction = void Function(
  ffi.Pointer<ffi.Char> source,
  ffi.Pointer<ffi.Char> reason,
  ffi.Pointer<ffi.Void> userData,
);

/// @brief Callback invoked when an MLS protocol failure occurs
/// @param source The source/component where the failure occurred
/// @param reason Human-readable failure reason
/// @param userData User-provided context pointer
typedef DAVEMLSFailureCallback =
    ffi.Pointer<ffi.NativeFunction<DAVEMLSFailureCallbackFunction>>;
typedef DAVEPairwiseFingerprintCallbackFunction = ffi.Void Function(
  ffi.Pointer<ffi.Uint8> fingerprint,
  ffi.Size length,
  ffi.Pointer<ffi.Void> userData,
);
typedef DartDAVEPairwiseFingerprintCallbackFunction = void Function(
  ffi.Pointer<ffi.Uint8> fingerprint,
  int length,
  ffi.Pointer<ffi.Void> userData,
);

/// @brief Callback invoked with the computed pairwise fingerprint for identity verification
/// @param fingerprint Pointer to fingerprint bytes (freed by the library after the callback returns)
/// @param length Length of fingerprint in bytes
/// @param userData User-provided context pointer
typedef DAVEPairwiseFingerprintCallback =
    ffi.Pointer<ffi.NativeFunction<DAVEPairwiseFingerprintCallbackFunction>>;
typedef DAVEEncryptorProtocolVersionChangedCallbackFunction = ffi.Void Function(
  ffi.Pointer<ffi.Void> userData,
);
typedef DartDAVEEncryptorProtocolVersionChangedCallbackFunction = void Function(
  ffi.Pointer<ffi.Void> userData,
);

/// @brief Callback invoked when the encryptor's protocol version changes
/// @param userData User-provided context pointer
typedef DAVEEncryptorProtocolVersionChangedCallback =
    ffi.Pointer<
      ffi.NativeFunction<DAVEEncryptorProtocolVersionChangedCallbackFunction>
    >;
typedef DAVELogSinkCallbackFunction = ffi.Void Function(
  ffi.UnsignedInt severity,
  ffi.Pointer<ffi.Char> file,
  ffi.Int line,
  ffi.Pointer<ffi.Char> message,
);
typedef DartDAVELogSinkCallbackFunction = void Function(
  DAVELoggingSeverity severity,
  ffi.Pointer<ffi.Char> file,
  int line,
  ffi.Pointer<ffi.Char> message,
);

/// @brief Custom log sink callback for receiving library log messages
/// @param severity Log severity level
/// @param file Source file name where log originated (freed by the library after the callback returns)
/// @param line Line number in source file
/// @param message Log message text (freed by the library after the callback returns)
typedef DAVELogSinkCallback =
    ffi.Pointer<ffi.NativeFunction<DAVELogSinkCallbackFunction>>;

/// @brief Statistics for encryption operations
final class DAVEEncryptorStats extends ffi.Struct {
  /// < Frames passed through without encryption
  @ffi.Uint64()
  external int passthroughCount;

  /// < Successful encryption count
  @ffi.Uint64()
  external int encryptSuccessCount;

  /// < Failed encryption count
  @ffi.Uint64()
  external int encryptFailureCount;

  /// < Total encryption duration
  @ffi.Uint64()
  external int encryptDuration;

  /// < Total encryption attempts
  @ffi.Uint64()
  external int encryptAttempts;

  /// < Maximum retry attempts for a single frame
  @ffi.Uint64()
  external int encryptMaxAttempts;

  /// < Encryptions skipped due to missing key
  @ffi.Uint64()
  external int encryptMissingKeyCount;
}

/// @brief Statistics for decryption operations
final class DAVEDecryptorStats extends ffi.Struct {
  /// < Frames passed through without decryption
  @ffi.Uint64()
  external int passthroughCount;

  /// < Successful decryption count
  @ffi.Uint64()
  external int decryptSuccessCount;

  /// < Failed decryption count
  @ffi.Uint64()
  external int decryptFailureCount;

  /// < Total decryption duration
  @ffi.Uint64()
  external int decryptDuration;

  /// < Total decryption attempts
  @ffi.Uint64()
  external int decryptAttempts;

  /// < Decryptions failed due to missing key
  @ffi.Uint64()
  external int decryptMissingKeyCount;

  /// < Decryptions failed due to invalid nonce
  @ffi.Uint64()
  external int decryptInvalidNonceCount;
}
