name: bonfire
description: "A modern take on the Discord Client"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <3.22.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  fireview:
    git: https://github.com/ericApostal/fireview

  firebridge:
    path: ../firebridge

  markdown_viewer:
    path: ../markdown_viewer

  firebridge_extensions:
    path: ../firebridge_extensions

  google_fonts: ^6.2.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # flutter_keyboard_visibility: ^6.0.0
  flutter_keyboard_size: ^1.0.1
  # relative_time: ^5.0.0
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1

  go_router: ^13.2.4
  flutter_prism: ^0.2.2

  media_kit:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: 652c49e02701bb6bb80953a6fdf650a5c8f002f9
      path: ./media_kit
  media_kit_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: 652c49e02701bb6bb80953a6fdf650a5c8f002f9
      path: ./media_kit_video
  media_kit_libs_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: 652c49e02701bb6bb80953a6fdf650a5c8f002f9
      path: ./libs/universal/media_kit_libs_video

  video_player_media_kit: ^1.0.5
  # media_kit_libs_android_video: any
  # media_kit_libs_ios_video: any
  # media_kit_libs_macos_video: any
  # media_kit_libs_windows_video: any
  # media_kit_libs_linux: any
  url_launcher: ^6.2.6
  sticky_headers: ^0.3.0+2
  flutter_svg: ^2.0.10+1
  bitsdojo_window: ^0.1.6
  collection: ^1.18.0
  http: ^1.2.1
  audioplayers: ^6.0.0
  file_icon: ^1.0.0
  internet_file: ^1.2.0
  file_selector: ^1.0.3
  dio: ^5.4.3+1
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  universal_platform: ^1.1.0
  dynamic_height_grid_view: ^0.0.4
  loading_animation_widget: ^1.2.1
  hive_ce: ^2.5.0
  universal_io: ^2.2.2

  flutter_circular_text: ^0.3.1
  flutter_thumbhash: ^0.1.0+1
  video_thumbnail_imageview: ^0.0.6
  flutter_cache_manager: ^3.4.0
  file_picker: ^8.0.7
  path: ^1.9.0
  flutter_localization: ^0.2.2
  video_player: ^2.9.2
  flutter_webrtc: ^0.12.11
  crypto: ^3.0.6

dependency_overrides:
  # webview_flutter_platform_interface: ^2.4.0
  fullscreen_window: ^1.1.0
  http: ^1.2.1
  meta: ^1.12.0

  media_kit:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: 652c49e02701bb6bb80953a6fdf650a5c8f002f9
      path: ./media_kit
  media_kit_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: 652c49e02701bb6bb80953a6fdf650a5c8f002f9
      path: ./media_kit_video
  media_kit_libs_video:
    git:
      url: https://github.com/media-kit/media-kit.git
      ref: 652c49e02701bb6bb80953a6fdf650a5c8f002f9
      path: ./libs/universal/media_kit_libs_video

  flutter_keyboard_visibility_web:
    git:
      url: https://github.com/raldhafiri/flutter_keyboard_visibility.git
      ref: master
      path: flutter_keyboard_visibility_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  custom_lint: ^0.7.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
