import 'dart:ffi' as ffi;
import 'dart:typed_data';

import 'package:ffi/ffi.dart' as pkg_ffi;

import 'opus_bindings_generated.dart' as bindings;

/// Coding mode hint passed to [OpusEncoder] - see opus.h's
/// `OPUS_APPLICATION_*` constants. Not generated by ffigen (they're
/// `#define` macros, not part of opus.h's own declarations), so mirrored
/// here from libopus's stable public ABI.
enum OpusApplication {
  /// Best quality at a given bitrate for voice signals - use this for voice
  /// chat.
  voip(2048),

  /// Best quality at a given bitrate for non-voice signals like music.
  audio(2049),

  /// Only use when lowest-achievable latency is what matters most.
  restrictedLowDelay(2051);

  final int value;
  const OpusApplication(this.value);
}

class OpusException implements Exception {
  const OpusException(this.code, this.message);
  final int code;
  final String message;

  @override
  String toString() => 'OpusException($code): $message';
}

void _checkOpusError(int code) {
  if (code < 0) {
    throw OpusException(code, 'libopus call failed with error code $code');
  }
}

final _encoderDestroyFinalizer =
    ffi.NativeFinalizer(ffi.Native.addressOf<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<bindings.OpusEncoder>)>>(bindings.opus_encoder_destroy).cast());

/// The largest Opus packet libopus can ever produce for a single frame, per
/// the RFC 6716 packet format - a safe fixed upper bound for output buffers.
const maxOpusPacketBytes = 1275;

/// Encodes 16-bit PCM audio to Opus. One instance per outgoing audio stream.
/// Must be [dispose]d.
class OpusEncoder implements ffi.Finalizable {
  /// [sampleRate] must be one of 8000, 12000, 16000, 24000, 48000 Hz (48000
  /// for Discord voice). [channels] is 1 (mono) or 2 (stereo interleaved).
  factory OpusEncoder({
    required int sampleRate,
    required int channels,
    OpusApplication application = OpusApplication.voip,
  }) {
    final errorPtr = pkg_ffi.malloc<ffi.Int>();
    try {
      final handle = bindings.opus_encoder_create(sampleRate, channels, application.value, errorPtr);
      _checkOpusError(errorPtr.value);
      if (handle == ffi.nullptr) throw const OpusException(-1, 'opus_encoder_create returned null');
      return OpusEncoder._(handle, channels);
    } finally {
      pkg_ffi.malloc.free(errorPtr);
    }
  }

  OpusEncoder._(this._handle, this._channels) {
    _encoderDestroyFinalizer.attach(this, _handle.cast(), detach: this);
  }

  final ffi.Pointer<bindings.OpusEncoder> _handle;
  final int _channels;
  bool _disposed = false;

  /// Encodes one frame of interleaved 16-bit PCM ([pcm].length must be
  /// `frameSize * channels`) into an Opus packet. [frameSize] is samples
  /// per channel and must be a valid Opus frame size for the encoder's
  /// sample rate (e.g. 960 for a 20ms frame at 48kHz).
  Uint8List encode(Int16List pcm, {required int frameSize}) {
    if (_disposed) throw StateError('OpusEncoder used after dispose()');

    final pcmPtr = pkg_ffi.malloc<ffi.Int16>(pcm.length);
    final outPtr = pkg_ffi.malloc<ffi.UnsignedChar>(maxOpusPacketBytes);
    try {
      pcmPtr.asTypedList(pcm.length).setAll(0, pcm);
      final writtenBytes = bindings.opus_encode(_handle, pcmPtr, frameSize, outPtr, maxOpusPacketBytes);
      _checkOpusError(writtenBytes);
      return Uint8List.fromList(outPtr.cast<ffi.Uint8>().asTypedList(writtenBytes));
    } finally {
      pkg_ffi.malloc.free(pcmPtr);
      pkg_ffi.malloc.free(outPtr);
    }
  }

  int get channels => _channels;

  void dispose() {
    if (_disposed) return;
    _disposed = true;
    _encoderDestroyFinalizer.detach(this);
    bindings.opus_encoder_destroy(_handle);
  }
}

final _decoderDestroyFinalizer =
    ffi.NativeFinalizer(ffi.Native.addressOf<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<bindings.OpusDecoder>)>>(bindings.opus_decoder_destroy).cast());

/// Decodes Opus audio to 16-bit PCM. One instance per incoming
/// participant/stream (decoder state is per-sender - don't share one
/// decoder across multiple SSRCs). Must be [dispose]d.
class OpusDecoder implements ffi.Finalizable {
  factory OpusDecoder({required int sampleRate, required int channels}) {
    final errorPtr = pkg_ffi.malloc<ffi.Int>();
    try {
      final handle = bindings.opus_decoder_create(sampleRate, channels, errorPtr);
      _checkOpusError(errorPtr.value);
      if (handle == ffi.nullptr) throw const OpusException(-1, 'opus_decoder_create returned null');
      return OpusDecoder._(handle, channels);
    } finally {
      pkg_ffi.malloc.free(errorPtr);
    }
  }

  OpusDecoder._(this._handle, this._channels) {
    _decoderDestroyFinalizer.attach(this, _handle.cast(), detach: this);
  }

  final ffi.Pointer<bindings.OpusDecoder> _handle;
  final int _channels;
  bool _disposed = false;

  int get channels => _channels;

  /// Decodes one Opus packet to interleaved 16-bit PCM ([frameSize] samples
  /// per channel). Pass `data: null` to signal a lost packet - libopus will
  /// synthesize concealment audio for [frameSize] samples instead.
  Int16List decode(Uint8List? data, {required int frameSize}) {
    if (_disposed) throw StateError('OpusDecoder used after dispose()');

    final dataPtr = data == null ? ffi.nullptr : pkg_ffi.malloc<ffi.UnsignedChar>(data.length);
    final pcmPtr = pkg_ffi.malloc<ffi.Int16>(frameSize * _channels);
    try {
      if (data != null) {
        dataPtr.cast<ffi.Uint8>().asTypedList(data.length).setAll(0, data);
      }
      final decodedSamples = bindings.opus_decode(
        _handle,
        dataPtr,
        data?.length ?? 0,
        pcmPtr,
        frameSize,
        0,
      );
      _checkOpusError(decodedSamples);
      return Int16List.fromList(pcmPtr.asTypedList(decodedSamples * _channels));
    } finally {
      if (dataPtr != ffi.nullptr) pkg_ffi.malloc.free(dataPtr);
      pkg_ffi.malloc.free(pcmPtr);
    }
  }

  void dispose() {
    if (_disposed) return;
    _disposed = true;
    _decoderDestroyFinalizer.detach(this);
    bindings.opus_decoder_destroy(_handle);
  }
}
