name: Flutter Build with Artifacts

on: [push, pull_request]

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        working-directory: ./bonfire
        run: flutter pub get
      - name: Run code generation
        working-directory: ./bonfire
        run: dart run build_runner build --delete-conflicting-outputs
      - name: Create CNAME file
        working-directory: ./bonfire
        run: echo "app.openbonfire.dev" > web/CNAME
      - name: Build and deploy
        uses: OpenBonfire/flutter-gh-pages@main
        with:
          workingDir: bonfire
          baseHref: /
          compileToWasm: true
          customArgs: --no-tree-shake-icons

  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        working-directory: ./bonfire
        run: flutter pub get

      - name: Run code generation
        working-directory: ./bonfire
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build Android APK
        working-directory: ./bonfire
        run: flutter build apk --no-tree-shake-icons -v

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: bonfire-android
          path: bonfire/build/app/outputs/flutter-apk/app-release.apk

      - name: Build Android App Bundle
        working-directory: ./bonfire
        run: flutter build appbundle --no-tree-shake-icons -v

      - name: Upload App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: bonfire-android-bundle
          path: bonfire/build/app/outputs/bundle/release/app-release.aab

  build-windows:
      runs-on: windows-latest
      steps:
        - name: Clone repository
          uses: actions/checkout@v2
          with:
            submodules: recursive

        - name: Set up Java 17
          uses: actions/setup-java@v2
          with:
            java-version: '17'
            distribution: 'adopt'

        # - name: Cleanup Visual Studio Installer
        #   continue-on-error: true
        #   run: |
        #     & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\InstallCleanup.exe"
        #   shell: pwsh

        # - name: Install Visual Studio 2022 Enterprise
        #   run: |
        #     Invoke-WebRequest -Uri https://aka.ms/vs/17/release.ltsc.17.10/vs_enterprise.exe -OutFile vs_enterprise.exe
        #     $process = Start-Process -FilePath '.\vs_enterprise.exe' -ArgumentList "--add", "Microsoft.VisualStudio.Workload.Azure", "--quiet", "--norestart", "--wait", "--includeRecommended" -Wait -PassThru
        #     Write-Output $process.ExitCode
        #     $process = Start-Process -FilePath '.\vs_enterprise.exe' -ArgumentList "--add", "Microsoft.VisualStudio.Workload.NativeDesktop", "--quiet", "--norestart", "--wait", "--includeRecommended" -Wait -PassThru
        #     Write-Output $process.ExitCode
        #   shell: pwsh

        # - name: Set up Visual Studio
        #   uses: microsoft/setup-msbuild@v1.1

        - name: Set up Flutter
          uses: subosito/flutter-action@v2
          with:
            channel: stable

        - name: Install dependencies
          working-directory: ./bonfire
          run: flutter pub get

        - name: Run code generation
          working-directory: ./bonfire
          run: dart run build_runner build --delete-conflicting-outputs

        - name: Build Windows
          working-directory: ./bonfire
          run: flutter build windows --no-tree-shake-icons -v

        - name: Upload Windows Executable
          uses: actions/upload-artifact@v4
          with:
            name: bonfire-windows
            path: bonfire/build/windows/x64/runner/Release/

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            ninja-build \
            libgtk-3-dev \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev \
            libunwind-dev \
            libmpv-dev \
            mpv \
            cmake \
            pkg-config \
            xclip \
            libx11-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxfixes-dev \
            libnss3-dev \
            libnspr4-dev \
            libatk1.0-dev \
            libatk-bridge2.0-dev \
            libdrm-dev \
            libgbm-dev \
            libasound2-dev \
            libvulkan-dev

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        working-directory: ./bonfire
        run: flutter pub get

      - name: Run code generation
        working-directory: ./bonfire
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Update CMakeLists.txt
        working-directory: ./bonfire
        run: |
          sed -i 's/target_link_libraries(${BINARY_NAME} PRIVATE PkgConfig::GTK/target_link_libraries(${BINARY_NAME} PRIVATE PkgConfig::GTK vulkan/' linux/CMakeLists.txt

      - name: Build Linux
        working-directory: ./bonfire
        env:
          LD_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
        run: flutter build linux --no-tree-shake-icons -v

      - name: Upload Linux Executable
        uses: actions/upload-artifact@v4
        with:
          name: bonfire-linux
          path: bonfire/build/linux/x64/release/bundle/
  build-ios:
      runs-on: macos-latest
      steps:
        - name: Clone repository
          uses: actions/checkout@v2
          with:
            submodules: recursive
            
        - name: Set up Java 17
          uses: actions/setup-java@v2
          with:
            java-version: '17'
            distribution: 'adopt'
            
        - name: Set up Flutter
          uses: subosito/flutter-action@v2
          with:
            channel: stable
            
        - name: Install dependencies
          working-directory: ./bonfire
          run: flutter pub get
          
        - name: Run code generation
          working-directory: ./bonfire
          run: dart run build_runner build --delete-conflicting-outputs
          
        - name: Setup Ruby for Fastlane
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: '3.0'
            bundler-cache: true
            
        - name: Build iOS
          working-directory: ./bonfire
          run: |
            flutter build ios --release --no-codesign --no-tree-shake-icons -v
            
        - name: Archive iOS build artifacts
          run: |
            cd bonfire/ios
            xcodebuild -workspace Runner.xcworkspace \
                      -scheme Runner \
                      -configuration Release \
                      -archivePath build/Runner.xcarchive \
                      archive \
                      -allowProvisioningUpdates \
                      CODE_SIGN_IDENTITY="" \
                      CODE_SIGNING_REQUIRED=NO \
                      CODE_SIGNING_ALLOWED=NO
                      
        - name: Create IPA file
          working-directory: ./bonfire/ios
          run: |
            mkdir -p Payload
            cp -R build/Runner.xcarchive/Products/Applications/Runner.app Payload
            zip -r app.ipa Payload
            
        - name: Upload IPA
          uses: actions/upload-artifact@v4
          with:
            name: bonfire-ios
            path: bonfire/ios/app.ipa
            
        - name: Upload Archive
          uses: actions/upload-artifact@v4
          with:
            name: bonfire-ios-archive
            path: bonfire/ios/build/Runner.xcarchive
  build-linux-arm:
    runs-on: ubuntu-latest
    container: ghcr.io/clickclickonsal/flutter-cross:3.16.0
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        working-directory: ./bonfire
        run: |
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs

      - name: Configure cross-build
        working-directory: ./bonfire
        run: |
          flutter config --enable-linux-desktop
          echo "Preparing ARM64 build environment..."
          sudo mkdir -p /usr/aarch64-linux-gnu
          sudo ln -s /usr/include /usr/aarch64-linux-gnu/include

      - name: Build Linux ARM64
        working-directory: ./bonfire
        run: |
          flutter build linux \
            --target-platform=linux-arm64 \
            --no-tree-shake-icons \
            -v \
            --target-sysroot=/usr/aarch64-linux-gnu \
            --linux-arch=arm64

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bonfire-linux-arm64
          path: bonfire/build/linux/arm64/release/bundle/