name: Flutter Build with Artifacts

on: [push, pull_request]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: bonfire-android
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Build Android App Bundle
        run: flutter build appbundle --no-tree-shake-icons

      - name: Upload App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: bonfire-android-bundle
          path: build/app/outputs/bundle/release/app-release.aab

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows --no-tree-shake-icons

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: bonfire-windows
          path: build/windows/x64/runner/Release/

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Install Linux dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libunwind-dev libmpv-dev mpv

      - name: Build Linux
        run: flutter build linux --no-tree-shake-icons

      - name: Upload Linux Executable
        uses: actions/upload-artifact@v4
        with:
          name: bonfire-linux
          path: build/linux/x64/release/bundle/

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build macOS
        run: flutter build macos --no-tree-shake-icons

      - name: Upload macOS Application
        uses: actions/upload-artifact@v4
        with:
          name: bonfire-macos
          path: build/macos/Build/Products/Release/*.app

  # build-ios:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Clone repository
  #       uses: actions/checkout@v2

  #     - name: Set up Java 17
  #       uses: actions/setup-java@v2
  #       with:
  #         java-version: '17'
  #         distribution: 'adopt'

  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: '3.22.3'

  #     - name: Install dependencies
  #       run: flutter pub get

  #     - name: Install CocoaPods
  #       run: sudo gem install cocoapods

  #     - name: Install iOS dependencies
  #       run: |
  #         cd ios
  #         pod install --repo-update

  #     - name: Build iOS
  #       run: |
  #         cd $GITHUB_WORKSPACE
  #         flutter build ios --release --no-codesign --no-tree-shake-icons

  #     - name: Upload iOS Archive
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: ios-archive
  #         path: build/ios/archive/MyApp.xcarchive

  #     - name: Build iOS IPA
  #       run: |
  #         cd $GITHUB_WORKSPACE/build/ios/archive/MyApp.xcarchive
  #         xcodebuild -exportArchive -archivePath MyApp.xcarchive -exportPath . -exportOptionsPlist ExportOptions.plist

  #     - name: Upload iOS IPA
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: ios-ipa
  #         path: build/ios/archive/MyApp.ipa
